name: instagram_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  cloud_firestore_odm: ^1.0.0-dev.86
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  get: ^4.6.6
  image_picker: ^1.1.1
  intela: ^0.0.4
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
